### ISSUE TITLE
Offline Charging

### ISSUE THREAD

**Issue by manjotsidhu** [manjotsidhu/DareDevil_a106#3]
While charging, without showing the battery logo (nor static and animated one) it just turn's on the device and if its plugged out then phone again turns down ...

**Comment by MagnusAlm** [comment]
As your kernel is based on Pablitos one.
Check this out :-)

https://github.com/Pablito2020/android_kernel_bq_krillin/issues/2

**Comment by manjotsidhu** [comment]
@MagnusAlm Thanks for the help... I ll try that patch ..

**Comment by manjotsidhu** [comment]
Thanks @MagnusAlm ... Offline Charging Fixed ... :+1:
